export default {
  login: 'MikheilMakasa',
  id: 106137950,
  node_id: 'U_kgDOBlOJXg',
  avatar_url: 'https://avatars.githubusercontent.com/u/106137950?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MikheilMakasa',
  html_url: 'https://github.com/MikheilMakasa',
  followers_url: 'https://api.github.com/users/MikheilMakasa/followers',
  following_url:
    'https://api.github.com/users/MikheilMakasa/following{/other_user}',
  gists_url: 'https://api.github.com/users/MikheilMakasa/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/MikheilMakasa/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MikheilMakasa/subscriptions',
  organizations_url: 'https://api.github.com/users/MikheilMakasa/orgs',
  repos_url: 'https://api.github.com/users/MikheilMakasa/repos',
  events_url: 'https://api.github.com/users/MikheilMakasa/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/MikheilMakasa/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mikheil Makasarashvili',
  company: null,
  blog: 'mikheil-makasarashvili.vercel.app/',
  location: 'Tbilisi, Georgia',
  email: null,
  hireable: null,
  bio: 'React Developer',
  twitter_username: null,
  public_repos: 40,
  public_gists: 0,
  followers: 1,
  following: 3,
  created_at: '2022-05-24T05:53:08Z',
  updated_at: '2022-11-07T11:05:51Z',
};
